### ISSUE TITLE
How to download the data from the Sharepoint

### ISSUE THREAD

**Issue by JinqianPan** [dddavid4real/HistGen#6] opened 2024-07-23 03:19 UTC
Hi,

I am working on how to download data from Sharepoint. The [official](https://support.microsoft.com/en-us/office/download-files-and-folders-from-onedrive-or-sharepoint-5c7397b7-19c7-4893-84fe-d02e8fa5df05) limit of Sharepoint's single zip download is 20GB, but it is obvious that this is far from enough. I wonder if there is any way to break through this limitation, so that could download data？

**Comment by dddavid4real** [comment] 2024-07-23 06:40
Hi. I guess you could go into folder dinov2, select all .pt files, and try downloading. Also, you could try to find some download tools for Onedrive SharePoint.

If you already downloaded the original WSI files (with .svs extension), you could use our provided DINOv2 feature extractor to extract the features.

**Comment by JinqianPan** [comment] 2024-07-23 20:19
Thank you for your reply! 

The first way, as previously mentioned, involves selecting all .pt files, which is feasible only when the file size is under 20GB; alternatively, could you divide the .pt files into 17 folders, each containing up to 20GB? So that we could download 17 times for different part of data.
I am still searching whether there is a tool could download the huge data from Onedrive or SharePoint. 
As for the final way, which involves downloading original WSI files, I am looking for a way to filter data from the GCD data portal to avoid downloading the entire 8.9PB of data.

**Comment by dddavid4real** [comment] 2024-07-24 06:30
If you are downloading to your personal PC, using Onedrive Windows/Mac to synchronize the data folder rather than downloading directly should be a better solution. After that, upload the files from your personal PC to linux server.

For TCGA Data Portal, you could simply download the .svs files of TCGA program using the filters provided by the website. There are many tutorials online.

**Comment by BenPashley** [comment] 2024-08-23 08:04
Hi and thank you for continuing help and support.

I'm trying to download the feature files as suggested but I cannot synchronize your data folder as it hasn't been explicitly shared with my one drive account.  If I provide my email would you be willing to do this or do you have an alternative suggestion? I've looked at other options including scraping or even downloading manually, but strangley I'm not even able to reorder your files by file size which would make this process easier.  I have downloaded the SVS files, but pre-processing them will take a considerable amount of time with my current resources.

**Comment by dddavid4real** [comment] 2024-08-23 11:05
> If

Hi, yes please attach your email and I will manually include your account to the viewer list.

**Comment by dddavid4real** [comment] 2024-08-23 11:06
> Hi and thank you for continuing help and support.
> 
> I'm trying to download the feature files as suggested but I cannot synchronize your data folder as it hasn't been explicitly shared with my one drive account. If I provide my email would you be willing to do this or do you have an alternative suggestion? I've looked at other options including scraping or even downloading manually, but strangley I'm not even able to reorder your files by file size which would make this process easier. I have downloaded the SVS files, but pre-processing them will take a considerable amount of time with my current resources.

Hi, yes please attach your email and I will manually include your account into the viewer list.

**Comment by BenPashley** [comment] 2024-08-23 12:08
Thanks.  ben.pashley@gmail.com

**Comment by dddavid4real** [comment] 2024-08-23 12:16
> Thanks. [ben.pashley@gmail.com](mailto:ben.pashley@gmail.com)

Access granted.

**Comment by BenPashley** [comment] 2024-08-23 12:29
Many thanks although I cannot see the share under my one drive account? Have you setup correctly?

**Comment by dddavid4real** [comment] 2024-08-23 12:41
> Many thanks although I cannot see the share under my one drive account? Have you setup correctly?

That's weird. Maybe try to use this link directly: https://hkustconnect-my.sharepoint.com/:f:/g/personal/zguobc_connect_ust_hk/EhmtBBT0n2lKtiCQt97eqcEBvO9WwNM3TL9x-7-kg_liuA?e=1N4FHk

**Comment by dddavid4real** [comment] 2024-08-23 12:51
> I can't see an option to specify my account. It only allows me to copy to an existing location in your one drive?

Is there any tutorial about syncing this folder to your Onedrive from my side?

**Comment by BenPashley** [comment] 2024-08-23 12:54
Try this.  You should be able to specify my email address as a viewer of the folder.  Thanks again for helping me with this.

https://support.microsoft.com/en-gb/office/share-onedrive-files-and-folders-9fcc2f7d-de0c-4cec-93b0-a82024800c07#ID0EDBJ=Share_with_specific_people

**Comment by dddavid4real** [comment] 2024-08-23 13:02
<img width="472" alt="Screenshot 2024-08-23 at 9 01 31 PM" src="https://github.com/user-attachments/assets/f435cb35-6ef5-46db-a996-bbc8924076ef">

See if it works this time?

**Comment by BenPashley** [comment] 2024-08-23 13:12
So strange!
<img width="1123" alt="Screenshot 2024-08-23 at 14 09 16" src="https://github.com/user-attachments/assets/e3fa8af4-b8ea-4fe2-8079-128487c61c59">
  Although I recevied your email I cannot see it in my one drive.  The issue is the limitation on downloading the zip.  Would it be at all possible to you win zip to create a multi-file zip? Say 5-10gb for each file. This will remove the issue and allow me to download the 30-50 separate files.  Winzip should make it easy to do this.

**Comment by BenPashley** [comment] 2024-08-23 13:13
10gb files seem to be ok.  I'm not sure what the limitation is? I think it's around 15-20gb.

**Comment by dddavid4real** [comment] 2024-08-23 13:25
Yeah the limitation of Onedrive can be disturbing. I will try if I can move these files to Google Drive or somewhere else. But this might take a lot of time since I didn't save these files locally on my PC. 

I suggest running the feature extraction code. And to speed up for that, you could run that script multiple times. For example, you could generate a reversed csv file and then run the feature extraction code on original csv and the reversed csv, which should save you half the time.

**Comment by BenPashley** [comment] 2024-08-23 13:56
Thanks for trying.  Good suggestion.  Will do.

**Comment by BenPashley** [comment] 2024-08-23 13:57
Would you mind removing my personal email address from the comments (is possible).

**Comment by dddavid4real** [comment] 2024-08-23 14:00
Sure thing. No worries.

**Comment by JinqianPan** [comment] 2024-08-23 14:05
> > Many thanks although I cannot see the share under my one drive account? Have you setup correctly?
> 
> That's weird. Maybe try to use this link directly: https://hkustconnect-my.sharepoint.com/:f:/g/personal/zguobc_connect_ust_hk/EhmtBBT0n2lKtiCQt97eqcEBvO9WwNM3TL9x-7-kg_liuA?e=1N4FHk
> 
> After you enter the link, choose all folders and files. After that, there is a button named "Copy to". Click that button should make it possible to copy the files to your own Onedrive.

The 'Copy to' bottom might only work  on your own account. It is weird that we could not copy to the files into our Onedrive.

**Comment by casperliuliuliu** [comment] 2024-11-09 08:59
The 'copy to' bottom seems only works when the one drive account is the same work or school account, which means only the one has HKUST account could access the files.

Would you willing to share those files through a personal account instead of organization account? I think this would solve the copy to problem.

Otherwise, I strongly suggest to upload all those files of image features, model weights to huggingface, which is a much more convenient and feasible platform for researchers!

Still, thank you for sharing and opening the access to the files, it greatly helps further AI development in the community.

I truly appreciate your work!

**Comment by dddavid4real** [comment] 2024-11-09 09:42
@casperliuliuliu Thank you for your suggestions! We will try Huggingface and hopefully can make all the data accessible soon.

**Comment by dddavid4real** [comment] 2024-11-10 04:59
We would like to update that we're currently uploading the dataset to HuggingFace, and it will take an estimated 7-10 days. Please stay tuned!

**Comment by dddavid4real** [comment] 2024-11-12 02:39
Hey guys we are glad to announce that all data (features, annotations, and model checkpoints) are now available on HuggingFace Datasets! See [here](https://huggingface.co/datasets/david4real/HistGen) for the brand-new look. 

We have updated the README files and will close this issue. Thank you for your patience and great suggestions! Feel free to open new issue thread for discussion if you run into any problem during downloading the data.

**Closed by dddavid4real** 2024-11-12 02:39 UTC

**Comment by casperliuliuliu** [comment] 2024-11-12 06:27
Thank you so much for the update! 🎉  
I really appreciate the quick response and support. Thanks again!
